build:
    dependencies:
        before:
            - pip install -r requirements-core.txt
    tests:
        override:
            -
                command: ./nosetests -v -e=*_lib_* --with-xunit --with-coverage --cover-erase --cover-package=stve
                coverage:
                    file: .coverage
                    config: .coveragerc
                    format: py-cc
filter:
    excluded_paths:
        - test/*

checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true
